###########################################
# BASE IMAGE
###########################################

FROM ubuntu AS hemlo

WORKDIR /app

COPY ./mohit_portfolio  /app

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip3 install django && \
    pip3 install -r requirements.txt

############################################
# HERE STARTS THE MAGIC OF MULTI STAGE BUILD
############################################

FROM gcr.io/distroless/python3

COPY --from=hemlo /app /app

ENV PYTHONPATH=/app 

EXPOSE 8000

ENTRYPOINT ["python"]

CMD ["/app/manage.py","runserver","0.0.0.0:8000"]


